// This file is generated by Slice Machine. Update with care!

import ImagesMedium from './ImagesMedium';
import News from './News';

export {
	ImagesMedium,
	News,
};

export const components = {
	images_medium: ImagesMedium,
	news: News,
};
